# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  # Build will compile APK, test APK and run tests, lint, etc.
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      TERM: dumb

    steps:
    - uses: actions/checkout@v2

    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    # Skipping app:lintDebug as the the code's starting state contains lint errors that are
    # corrected when implementing the codelab.
    - name: Build and check
      working-directory: constraint-layout-start
      run: ./gradlew assembleDebug assembleDebugAndroidTest testDebug

    - name: Upload build reports
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: build-reports
        path: constraint-layout-start/app/build/reports

    - name: Copy test results
      working-directory: constraint-layout-start
      if: always()
      run: |
        mkdir -p junit
        find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} junit/ \;
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: junit-results
        path: constraint-layout-start/junit
